apiVersion: v1
kind: Secret
metadata:
  name: httpd-sftp
  labels:
    app: httpd-sftp
type: Opaque
stringData:
  SCRIPT_NAME: L2ZpbGVz
  SFTP_DIR: bWVkaWE=
  SFTP_HOST: d2ViLWFwcGxpY2F0aW9uLTMtdm0ucG9jYXBwLnN2Yy5jbHVzdGVyLmxvY2Fs
  SFTP_PASS: cGFzc3dvcmQ=
  SFTP_USER: c2Z0cC11c2Vy